In [1]:
import numpy as np

## **Creating an array: Several Notes** ##
### **A. Create an array from a list** ##

In [2]:
np.array([1, 2, 3, 4, 5]).dtype

dtype('int32')

In [3]:
pythonList = [1, 2, 3, 4, 5]
numpyArray = np.array(pythonList) # Convert list to array
numpyArray

array([1, 2, 3, 4, 5])

### **B. Array is not a list: only contain same type of data** ###

In [4]:
#prove that array are different from list, and only contain the same type of data
np.array([3.12, 2, 4, 6, 9])

array([3.12, 2.  , 4.  , 6.  , 9.  ])

In [5]:
arr_1 = np.array([1, 2, 3, 4, 5])

In [7]:
arr_2 = np.array(['one', 'two', 'three', 'four'])

In [8]:
arr_3 = np.array([1, 2, 3, 'four', 'five'])

In [9]:
arr_3

array(['1', '2', '3', 'four', 'five'], dtype='<U11')

In [10]:
# Other Difference: math operational
arrays = np.arange(1, 11)
lists = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [11]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
arr = np.arange(1, 10)
arr+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
## If list, this function can not be done

### **C. Specify The Data Types** ###

In [14]:
#Specify a data type of an array usubg dtyoe
np.array([2, 3, 4, 5, 6, 8.987], dtype='int64')

array([2, 3, 4, 5, 6, 8], dtype=int64)

### **D. Create a Multidimensional Array** ###

In [15]:
np.array([range(i, i+4) for i in [2, 6, 10, 14]]) # List Comprehension

# range (2, 2+4) ---> 2, 6
# range (6, 6+4) ---> 2, 10
# range (10, 10+4) ---> 10, 14
# range (14, 14+4) ---> 14, 18

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [16]:
np.array([range(i, i+4) for i in [2, 6, 10, 14]])

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

### **Built-in Methods** ###

In [17]:
# Creating an array containing list of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
# Creating an Array with a certain range:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
np.arange(5,12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [20]:
np.arange(1, 62, 10) # Start, Stop Exclusive, step

array([ 1, 11, 21, 31, 41, 51, 61])

In [21]:
# Creating an array containing a list of one:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
# Creating an Array with an evenly divided range
np.linspace(1, 100, 10) # start, sto inclusivem, size or step

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [23]:
# specifying Data Types
np.linspace(0, 100, 11, dtype='int64')

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100], dtype=int64)

In [27]:
# Creating an Array containing a sample (or samples) from the 'Standart Normal' distribution
example = np.random.randn(10)

In [28]:
example

array([-0.19847812, -0.32228353, -1.47930663,  1.39146856, -0.54581857,
        0.48170416,  0.08499957,  0.16999716,  0.71436829, -0.78838754])

In [29]:
np.random.randn(5,5)

array([[-0.53964375, -0.04741938, -0.03939823,  0.15256919,  0.59991239],
       [ 0.50354615,  0.76504831,  0.38218206,  0.64187259, -0.1824616 ],
       [ 0.44942451,  1.762928  , -0.11678809,  0.38759513,  0.1302628 ],
       [-1.75699896, -0.80143855, -0.83381824,  0.01199356, -0.98793385],
       [-0.07196332,  1.75584767,  1.10938037, -2.64249263,  0.08525821]])

In [30]:
np.random.randint(2, 50, [3,3]) # Generate random number from 2 to 50 with dimension 3 by 3

array([[34,  9, 26],
       [20, 17,  9],
       [34,  4, 45]])

In [31]:
# Creating an Array containing a random integers from 'low' (inclusive) to 'high' (exclusive)
np.random.randint(2, 100, [3,10]) # low, high, size

array([[77, 26, 79, 81, 57, 72, 41, 99, 13, 61],
       [26, 42, 73, 14, 84, 71, 36, 68, 49, 35],
       [54, 24, 11, 47, 97, 37, 26, 61, 77, 40]])

In [32]:
random = np.random.randint(100, size = 10)

In [33]:
random

array([77, 49, 63,  0, 13, 18, 16, 97, 67, 66])

In [34]:
np.random.randint(100)

29

In [35]:
random.sum()

466

In [36]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
a.reshape(3,5) # Change the dimension to 3 rows, 5 columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [38]:
b2 = a.copy()
b2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
b1 = a[2:7]
b1

array([3, 4, 5, 6, 7])

In [40]:
b1[0] = 100
b1

array([100,   4,   5,   6,   7])

In [41]:
a

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15])

In [42]:
b2[0] = 1550
b2

array([1550,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15])

In [43]:
a

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15])

In [44]:
#View log
np.lookfor('log')

Search results for 'log'
------------------------
numpy.log
    Natural logarithm, element-wise.
numpy.log2
    Base-2 logarithm of `x`.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element-wise.
numpy.logspace
    Return numbers spaced evenly on a log scale.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.logical_or
    Compute the truth value of x1 OR x2 element-wise.
numpy.logical_and
    Compute the truth value of x1 AND x2 element-wise.
numpy.logical_not
    Compute the truth value of NOT x element-wise.
numpy.logical_xor
    Compute the truth value of x1 XOR x2, element-wise.
numpy.ma.log
    Natural logarithm, element-wise.
numpy.ma.log2
    Base-2 logarithm of `x`.
numpy.ma.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.rec

### **Array Indexing** ###

In [45]:
np.random.seed(0) # Seed for reproducibility
array1 = np.random.randint(10, size=6) # One Dimensional Array
array2 = np.random.randint(10, size=(3, 4)) # Two Dimensional Array
print([print(i, '\n ----------------') for i in [array1, array2]])

[5 0 3 3 7 9] 
 ----------------
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 
 ----------------
[None, None]


In [46]:
#Indexing from one dimensional array
print(array1[0])
print(array1[2:5])
print(array1[:-2])

5
[3 3 7]
[5 0 3 3]


In [47]:
#Indexing Multi Dimensional Array
print(array2[1,2])

8
